const blogContent = {
  postsPerPage: 12,
  categories: ['All', 'Outsourcing', 'Audit'],
  posts: [
    {
      slug: 'outsourcing-tax-return-preparation',
      title: 'Outsourcing Tax Return Preparation: Step-by-Step Playbook for Scaling Your Accounting Firm Fast',
      category: 'Outsourcing',
      image: '/images/blog/post1.jpg',
      date: '2025-12-15',
      content: '<h2>Introduction</h2><p>A comprehensive guide to outsourcing tax return preparation for accounting firms looking to scale efficiently.</p>',
    },
    {
      slug: 'outsourced-accounting',
      title: 'Outsourced Accounting Made Practical: A Scalable Finance Model for Small Businesses, Startups, and Growing Firms',
      category: 'Outsourcing',
      image: '/images/blog/post2.jpg',
      date: '2025-12-13',
      content: '<h2>Introduction</h2><p>How outsourced accounting provides a scalable finance model for growing businesses.</p>',
    },
    {
      slug: 'uk-accounting-firm-growth-guide',
      title: 'The Ultimate Guide to Outsourcing Tax Return Preparation for UK Accounting Firm Growth',
      category: 'Outsourcing',
      image: '/images/blog/post3.jpg',
      date: '2025-12-11',
      content: '<h2>Introduction</h2><p>UK-focused guide on leveraging outsourcing for accounting firm growth.</p>',
    },
    {
      slug: 'outsource-bookkeeping',
      title: 'Outsource Bookkeeping Like a Pro: Step-by-Step Guide, Best Practices, and What to Avoid',
      category: 'Outsourcing',
      image: '/images/blog/post4.jpg',
      date: '2025-12-09',
      content: '<h2>Introduction</h2><p>Best practices for outsourcing bookkeeping services effectively.</p>',
    },
    {
      slug: 'internal-audit-outsourcing',
      title: 'Internal Audit Outsourcing: The Complete Guide for Modern Accounting Firms',
      category: 'Audit',
      image: '/images/blog/post5.jpg',
      date: '2025-12-07',
      content: '<h2>Introduction</h2><p>Complete guide to internal audit outsourcing for modern firms.</p>',
    },
    {
      slug: 'corporate-reporting-2025',
      title: 'Corporate Reporting in 2025: What the FRC\'s Annual Review Tells Us — and How CapacityHive Can Help Firms Stay Ahead',
      category: 'Audit',
      image: '/images/blog/post6.jpg',
      date: '2025-12-05',
      content: '<h2>Introduction</h2><p>Analysis of the FRC annual review and implications for audit firms.</p>',
    },
    {
      slug: 'benchmarking-capacity',
      title: 'Benchmarking Capacity: How Do You Stack Up Against High-Performing Firms?',
      category: 'Audit',
      image: '/images/blog/post1.jpg',
      date: '2025-12-03',
      content: '<h2>Introduction</h2><p>How to benchmark your firm\'s capacity against industry leaders.</p>',
    },
    {
      slug: 'uk-stewardship-code-2026',
      title: 'The UK Stewardship Code 2026: A Comprehensive Overview',
      category: 'Audit',
      image: '/images/blog/post2.jpg',
      date: '2025-12-01',
      content: '<h2>Introduction</h2><p>Overview of the UK Stewardship Code and its implications.</p>',
    },
    {
      slug: 'cpa-firms-benchmarking',
      title: 'Benchmarking Capacity: How Do You Compare to High-Performing CPA Firms?',
      category: 'Audit',
      image: '/images/blog/post3.jpg',
      date: '2025-11-29',
      content: '<h2>Introduction</h2><p>CPA-focused capacity benchmarking guide.</p>',
    },
    {
      slug: 'broker-dealer-audits',
      title: 'Three Out of Four Broker-Dealer Audits Are Falling Short — And What It Means for Audit Delivery Models',
      category: 'Audit',
      image: '/images/blog/post4.jpg',
      date: '2025-11-27',
      content: '<h2>Introduction</h2><p>Analysis of broker-dealer audit quality and delivery model implications.</p>',
    },
    {
      slug: 'auditing-made-simple',
      title: 'Auditing Made Simple: The FRC\'s New Guidance for Smaller and Less Complex Entities',
      category: 'Audit',
      image: '/images/blog/post5.jpg',
      date: '2025-11-25',
      content: '<h2>Introduction</h2><p>Understanding the FRC\'s simplified guidance for smaller entities.</p>',
    },
    {
      slug: 'audit-quality-2025',
      title: 'Audit Quality in 2025: What the FRC Report Reveals — and Why Audit Capacity Needs a Rethink',
      category: 'Audit',
      image: '/images/blog/post6.jpg',
      date: '2025-11-23',
      content: '<h2>Introduction</h2><p>Key findings from the FRC report on audit quality and capacity.</p>',
    },
  ],
}

export default blogContent
